### ISSUE TITLE
rake test does not succeed on 3.14.2

### ISSUE THREAD

**Issue by mtasaka** [seattlerb/hoe#69] opened 2015-09-21 15:06 UTC
With hoe 3.14.2:
```
$ rake test
.........E..................

Finished in 0.249113s, 128.4557 runs/s, 381.3530 assertions/s.

  1) Error:
TestHoe#test_extensions:
NameError: undefined local variable or method `clean_globs' for #<Hoe:0x00561f76c51548>
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/lib/hoe/compiler.rb:53:in `block in define_compiler_tasks'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/lib/hoe/compiler.rb:52:in `each'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/lib/hoe/compiler.rb:52:in `define_compiler_tasks'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/lib/hoe.rb:730:in `block in load_plugin_tasks'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/lib/hoe.rb:724:in `each'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/lib/hoe.rb:724:in `load_plugin_tasks'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/lib/hoe.rb:808:in `post_initialize'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/lib/hoe.rb:390:in `spec'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/test/test_hoe.rb:15:in `hoe'
    /home/tasaka1/rpmbuild/fedora-specific/TMP/rubygem-hoe/master/rubygem-hoe/3.14.2/TMP/test/test_hoe.rb:367:in `block in test_extensions'

32 runs, 95 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
```

3.14.0 does not see this error, not tested 3.14.1

**Comment by tenderlove** [comment] 2015-09-21 17:46
Can you give more details about how to reproduce this error?  I tried running `rake test` from the project root on FC22 with Ruby 2.2.2, and I'm not getting any errors.

**Comment by zenspider** [comment] 2015-09-21 19:55
I'm guessing it is some sort of file system ordering difference. Works for me on osx

**Comment by mtasaka** [comment] 2015-09-22 06:18
Difficult. I am using Fedora 23 (x86_64), and it seems that rake test sometimes succeeds. So this seems some random issue.

**Comment by zenspider** [comment] 2015-09-23 01:24
I'm traveling and don't have a linux slice available to test against. I would call this benign tho. I'm passing 100% on my FS. When I get a linux slice to run, I'll take a whack at this.

**Comment by zenspider** [comment] 2015-09-23 20:58
This also doesn't include the full test output. If it did, I could try to see if it would reproduce for that `--seed` value.

I'm unable to reproduce this on lubuntu. I suspect this is specific to your system/setup. Without a repro, I'm going to have to close this.

**Comment by havenwood** [comment] 2015-09-23 21:26
I'm not able to reproduce this with Fedora 23 (x86_64) with Ruby 2.2.3.

**Comment by zenspider** [comment] 2015-09-29 18:45
@mtasaka anything?

**Comment by zenspider** [comment] 2015-10-14 00:21
No response. Closing.

**Closed by zenspider** 2015-10-14 00:21 UTC

**Comment by tonytonyjan** [comment] 2016-12-08 09:39
same here with ruby 2.3.1, rake 12.0.0 in 72f1852

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ rake --version
rake, version 12.0.0
$ rake test                                                                                                                                                fish-2 | 0 < 17:35:34
/Users/tonytonyjan/.rbenv/versions/2.3.1/bin/ruby -w -I../../minitest/dev/lib:lib:bin:test:. -e 'require "rubygems"; gem "minitest"; require "minitest/autorun"; require "test/test_hoe_test.rb"; require "test/test_hoe.rb"; require "test/test_hoe_debug.rb"; require "test/test_hoe_gemcutter.rb"; require "test/test_hoe_package.rb"; require "test/test_hoe_publish.rb"; require "test/test_hoe_test.rb"' --
Run options: --seed 60440

# Running:

............................E...

Finished in 2.501766s, 12.7910 runs/s, 37.9732 assertions/s.

  1) Error:
TestHoe#test_extensions:
NameError: undefined local variable or method `clean_globs' for #<Hoe:0x007fde1a13cbf8>
    /Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe/compiler.rb:53:in `block in define_compiler_tasks'
    /Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe/compiler.rb:52:in `each'
    /Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe/compiler.rb:52:in `define_compiler_tasks'
    /Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe.rb:729:in `block in load_plugin_tasks'
    /Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe.rb:723:in `each'
    /Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe.rb:723:in `load_plugin_tasks'
    /Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe.rb:808:in `post_initialize'
    /Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe.rb:390:in `spec'
    /Users/tonytonyjan/Dropbox/codes/hoe/test/test_hoe.rb:15:in `hoe'
    /Users/tonytonyjan/Dropbox/codes/hoe/test/test_hoe.rb:367:in `block in test_extensions'

32 runs, 95 assertions, 0 failures, 1 errors, 0 skips
rake aborted!
Command failed with status (1): [/Users/tonytonyjan/.rbenv/versions/2.3.1/b...]
/Users/tonytonyjan/Dropbox/codes/hoe/lib/hoe/test.rb:83:in `block in define_test_tasks'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by tonytonyjan** [comment] 2016-12-08 09:49
FYI, I ran 11 times `rake test`, 2 passed, 9 failed, pretty weird.
