### ISSUE TITLE
Installing Hoe on a NFS partition

### ISSUE THREAD

**Issue by EHadoux** [seattlerb/hoe#66] opened 2015-02-06 19:27 UTC
Hi,

there is an issue with hoe and minitest.
```gem install``` does not work if the directory is on a NFS partition.
See seattlerb/minitest#435 and rubygems/rubygems#1161

Many thanks

**Comment by zenspider** [comment] 2015-02-07 01:27
This is a dupe of #63, which is a dupe of seattlerb/minitest#435. Fixing one will fix them all (guessing, but I'll handle it either way).

**Closed by zenspider** 2015-02-07 01:27 UTC

**Comment by EHadoux** [comment] 2015-02-07 10:55
My bad, thank you.
